INSERT INTO authority(id, name) VALUES (1, 'FRONT_READ');
INSERT INTO authority(id, name) VALUES (2, 'FRONT_WRITE');
INSERT INTO authority(id, name) VALUES (3, 'MIDDLE_READ');
INSERT INTO authority(id, name) VALUES (4, 'MIDDLE_WRITE');
INSERT INTO user_(id, user_name, password, account_expired, account_locked, credentials_expired, enabled) VALUES (1, 'admin', '$2a$08$qvrzQZ7jJ7oy2p/msL4M0.l83Cd0jNsX6AJUitbgRXGzge4j035ha', FALSE, FALSE, FALSE, TRUE);
INSERT INTO user_(id, user_name, password, account_expired, account_locked, credentials_expired, enabled) VALUES (2, 'reader', '$2a$08$dwYz8O.qtUXboGosJFsS4u19LHKW7aCQ0LXXuNlRfjjGKwj5NfKSe', FALSE, FALSE, FALSE, TRUE);
INSERT INTO users_authorities(user_id, authority_id) VALUES (1, 1);
INSERT INTO users_authorities(user_id, authority_id) VALUES (1, 2);
INSERT INTO users_authorities(user_id, authority_id) VALUES (1, 3);
INSERT INTO users_authorities(user_id, authority_id) VALUES (1, 4);
INSERT INTO users_authorities(user_id, authority_id) VALUES (2, 1);
INSERT INTO users_authorities(user_id, authority_id) VALUES (2, 3);
INSERT INTO oauth_client_details(client_id, resource_ids, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity) VALUES('spring-security-oauth2-read-client', 'resource-server-rest-api', '$2a$04$WGq2P9egiOYoOFemBRfsiO9qTcyJtNRnPKNBl5tokP7IP.eZn93km', 'read', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);
INSERT INTO oauth_client_details(client_id, resource_ids, client_secret, scope, authorized_grant_types, authorities, access_token_validity, refresh_token_validity)   VALUES('spring-security-oauth2-read-write-client', 'resource-server-rest-api', '$2a$04$soeOR.QFmClXeFIrhJVLWOQxfHjsJLSpWrU1iGxcMGdu.a5hvfY4W', 'read,write', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('BASE', 1, '기본 타이핑 1', 10);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('BASE', 2, '기본 타이핑 2', 20);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('BASE', 3, '기본 타이핑 3', 30);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('WORD', 1, '단어 타이핑 1', 40);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('WORD', 2, '단어 타이핑 2', 50);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('WORD', 3, '단어 타이핑 3', 60);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('PARAGRAPH', 1, '문장 타이핑 1', 70);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('PARAGRAPH', 2, '문장 타이핑 2', 80);
INSERT INTO typing_step(subject, step, step_name, step_score) VALUES('PARAGRAPH', 3, '문장 타이핑 3', 90);